
name: CI Test

on: [push, pull_request]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hello World
        run: echo "🚀 CI/CD is working!"